-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS WINENOT_WH
  WITH WAREHOUSE_SIZE = XSMALL AUTO_SUSPEND = 60 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = TRUE;

-- Database + Schemas
CREATE DATABASE IF NOT EXISTS WINENOT;
CREATE SCHEMA IF NOT EXISTS WINENOT.STAGING;
CREATE SCHEMA IF NOT EXISTS WINENOT.DEV;
CREATE SCHEMA IF NOT EXISTS WINENOT.PROD;

-- Context
USE WAREHOUSE WINENOT_WH;
USE DATABASE WINENOT;

-- RAW tables in STAGING
CREATE OR REPLACE TABLE STAGING.PRODUCTS_RAW (
  ID INTEGER, REFERENCE STRING, COLOR STRING, COUNTRY STRING, REGION STRING,
  APPELLATION STRING, VINTAGE INTEGER, GRAPES STRING, ALCOHOL_PERCENT FLOAT,
  BOTTLE_SIZE_L FLOAT, SWEETNESS STRING, TANNIN STRING, ACIDITY STRING,
  RATING INTEGER, PRICE_EUR FLOAT, PRODUCER STRING, STOCK_QUANTITY INTEGER
);
CREATE OR REPLACE TABLE STAGING.CONSUMERS_RAW (
  ID INTEGER, NAME STRING, EMAIL STRING, COUNTRY STRING, CREATED_AT TIMESTAMP_NTZ
);
CREATE OR REPLACE TABLE STAGING.ORDERS_RAW (
  ID INTEGER, CONSUMER_ID INTEGER, PRODUCT_ID INTEGER, QTY INTEGER, CHANNEL STRING, ORDER_TS TIMESTAMP_NTZ
);

-- DEV destination (curated mirrors for now)
CREATE OR REPLACE TABLE DEV.PRODUCTS LIKE STAGING.PRODUCTS_RAW;
CREATE OR REPLACE TABLE DEV.CONSUMERS LIKE STAGING.CONSUMERS_RAW;
CREATE OR REPLACE TABLE DEV.ORDERS   LIKE STAGING.ORDERS_RAW;

-- Simple promotion step (DEV <- STAGING)
CREATE OR REPLACE PROCEDURE DEV.SP_REFRESH()
RETURNS STRING LANGUAGE SQL AS
$$
  MERGE INTO DEV.PRODUCTS t USING STAGING.PRODUCTS_RAW s ON t.ID = s.ID
    WHEN MATCHED THEN UPDATE SET * = s.*
    WHEN NOT MATCHED THEN INSERT *;
  MERGE INTO DEV.CONSUMERS t USING STAGING.CONSUMERS_RAW s ON t.ID = s.ID
    WHEN MATCHED THEN UPDATE SET * = s.*
    WHEN NOT MATCHED THEN INSERT *;
  MERGE INTO DEV.ORDERS t USING STAGING.ORDERS_RAW s ON t.ID = s.ID
    WHEN MATCHED THEN UPDATE SET * = s.*
    WHEN NOT MATCHED THEN INSERT *;
  RETURN 'OK';
$$;

-- Optional compatibility (so your existing teacher SQL that reads UAT.WINE_CATALOG still works)
CREATE SCHEMA IF NOT EXISTS WINENOT.UAT;
CREATE OR REPLACE VIEW UAT.WINE_CATALOG AS SELECT * FROM DEV.PRODUCTS;

-- PROD tables (empty for now; your transform will fill WINENOT.PRD.WINES)
CREATE OR REPLACE TABLE PROD.WINES LIKE STAGING.PRODUCTS_RAW;
